/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spore_jni_ImageUtilEngine */

#ifndef _Included_com_spore_jni_ImageUtilEngine
#define _Included_com_spore_jni_ImageUtilEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spore_jni_ImageUtilEngine
 * Method:    decodeYUV420SP
 * Signature: ([BII)[I
 */
jint Java_com_powervision_video_media_codec_StreamCodec_decodeYUV420SP_1
  (JNIEnv * env, jobject thiz, jintArray dat, jbyteArray buf, jint width, jint height);

#ifdef __cplusplus
}
#endif
#endif
