/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spore_jni_ImageUtilEngine */

#ifndef _Included_com_spore_jni_ImageUtilEngine
#define _Included_com_spore_jni_ImageUtilEngine
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif
